spring:
  application:
    name: RENTAL-SERVICE
  datasource:
    username: postgres
    password: '123456'
    url: jdbc:postgresql://localhost:5432/rental-db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    producer:
      bootstrap-servers: http://localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
server:
  port: 0
resilience4j:
  circuitbreaker:
    instances:
      inventory-service:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50 #Başarısızlık oranı eşiğe eşit veya eşikten yüksek olduğunda, CircuitBreaker açık konuma geçer ve kısa devre çağrılarını başlatır.
        minimumNumberOfCalls: 5 #CircuitBreaker'ın hata oranını veya yavaş çağrı oranını hesaplayabilmesi için gerekli olan (kayan pencere periyodu başına) minimum çağrı sayısını yapılandırır.
        automaticTransitionFromOpenToHalfOpenEnabled: true
        #true olarak ayarlanırsa, CircuitBreaker'ın otomatik olarak açık durumdan yarı açık duruma geçeceği ve geçişi tetiklemek için herhangi bir arama gerekmediği anlamına gelir. WaitDurationInOpenState geçtikten sonra bunları HALF_OPEN'e geçirmek üzere CircuitBreakers'ın tüm örneklerini izlemek için bir iş parçacığı oluşturulur. Oysa false olarak ayarlanırsa, HALF_OPEN'e geçiş yalnızca bir çağrı yapıldığında, waitDurationInOpenState geçildikten sonra bile gerçekleşir.
        #Buradaki avantaj, hiçbir iş parçacığının tüm Devre Kesicilerin durumunu izlememesidir.
        waitDurationInOpenState: 5s #Devre Kesicinin açıktan yarı açık duruma geçmeden önce beklemesi gereken süre.
        permittedNumberOfCallsInHalfOpenState: 3 #CircuitBreaker yarı açıkken izin verilen aramaların sayısını yapılandırır.
        slidingWindowSize: 10 #CircuitBreaker kapatıldığında aramaların sonucunu kaydetmek için kullanılan sürgülü pencerenin boyutunu yapılandırır.
        slidingWindowType: COUNT_BASED #Kayan pencere COUNT_BASED ise, son çağrılar kaydedilir ve toplanır. Kayan pencere TIME_BASED ise, son saniyelerdeki aramalar kaydedilir ve toplanır.slidingWindowSize
  #slidingWindowSize

  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 5s

